apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: q2
  name: q2
spec:
  containers:
  - image: nginx
    name: q2
    resources: {}
    envFrom:
    - configMapRef:
        name: cmq1
  restartPolicy: Always
