apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: q1
  name: q1
spec:
  containers:
  - image: nginx
    name: q1
    resources: {}
    env:
    - name: DB_HOST
      valueFrom: 
        configMapKeyRef:
          name: cmq1    
          key: DB_HOST   
    - name: DB_PORT
      valueFrom: 
        configMapKeyRef:
          name: cmq1    
          key: DB_PORT   
    - name: DB_ENV
      valueFrom: 
        configMapKeyRef:
          name: cmq1    
          key: DB_ENV    
  restartPolicy: Always
