apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: q3
  name: q3
spec:
  containers:
  - image: nginx
    name: q3
    volumeMounts:
       - name: config
         mountPath: /config
         readOnly: true
    resources: {}
  restartPolicy: Always
  volumes:
     - name: config
       configMap: 
          name: cmq1

