apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  namespace: rc
  labels:
    rn: nwp1
  name: nwp1
spec:
  containers:
  - image: nginx
    name: nwp1 
    resources:
      requests:
         cpu: "500m"
         memory: "256Mi"
      limits:
         cpu: "1"
         memory: "1024Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
