apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: q3
  name: q3
spec:
  containers:
  - image: nginx 
    name: q3
    resources: {}
    volumeMounts: 
       - name : config
         mountPath: "/config"
         readOnly: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name : config
      configMap :
        name : econfig
status: {}
