apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: db-app
  name: db-app
spec:
  containers:
  - image: phpmyadmin:latest
    name: db-app
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
