apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: basic
  name: basic
  namespace: database
spec:
  containers:
  - image: phpmyadmin
    name: basic
    resources: {}
    ports:
     - containerPort: 80
    env:
     - name: PMA_HOST
       value: "localhost"
     - name: PMA_PORT
       value: "3306"
  initContainers:
  - image: mysql
    name: start
    command: ['sh', '-c','mysql -u root -proot -e "Create Database if not exist mulla";']
    env:
     - name: MYSQL_ROOT_PASSWORD
       value: root
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
