apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: init
  name: init
spec:
  containers:
  - image: nginx
    name: init
    resources: {}
    volumeMounts: 
       - name: shared
         mountPath: /config
         readOnly: true
  initContainers:
  - image: busybox
    name: start
    resources: {}
    volumeMounts: 
       - name: shared
         mountPath: /config
    command:
       ['sh', '-c','echo "Intilization" > /config/init.txt']
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: shared
      emptyDir: {}
status: {}
