apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: myapp
  name: myapp-pod
spec:
  containers:
  - image: nginx
    name: myapp-pod
    resources: {}
    securityContext: 
      runAsUser: 1000
      runAsGroup: 3000
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
