apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: cng
  name: cng
spec:
  containers:
  - image: bitnami/nginx
    name: cng
    resources: {}
    securityContext:
      runAsNonRoot: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
