apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: fa
  name: fa
spec:
  containers:
  - image: bitnami/nginx
    name: fa
    resources: {}
    securityContext:
      runAsNonRoot: true
    volumeMounts: 
      - name: access-file
        mountPath: /config
        readOnly: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  securityContext:
    fsGroup: 3500
  volumes:
    - name: access-file
      emptyDir : {}
status: {}
