apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ng
  name: ng
spec:
  containers:
  - image: nginx
    name: ng
    resources: {}
    securityContext:
       runAsNonRoot: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
