apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sc
  name: sc
spec:
  containers:
  - image: nginx
    name: sc
    ports:
    - containerPort: 80
    resources: {}
    securityContext: 
      privileged: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  hostNetwork: true
status: {}
