apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: data-exachange
  name: data-exachange
spec:
  volumes:
  - name: vol
    emptyDir: {}
   
  containers:
  - image: busybox
    name: main-app
    command: ['sh', '-c','counter=1; while true; do touch "/var/app/data/$counter-data.txt"; counter=$((counter+1)); sleep 30; done;']
    volumeMounts:
      - name: vol
        mountPath: /var/app/data/
  - image: busybox
    name: sidecar
    command: ['sh', '-c','while true; do ls -d /var/app/data/*-data.txt | wc -l; sleep 30; done;']
    volumeMounts:
      - name: vol
        mountPath: /var/app/data/
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
