apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: auth
  name: auth
spec:
  containers:
  - image: nginx
    name: auth
    resources: {}
    env: 
      - name: API_SECRET
        valueFrom:
          secretKeyRef:
            name : as
            key : API_KEY
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
