apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ra
  name: ra
spec:
  containers:
  - image: bitnami/nginx
    name: ra
    resources: {}
    securityContext:
      runAsUser: 501
      runAsGroup: 20
    volumeMounts:
      - name: limit-access
        mountPath: /etc/secrets
        readOnly: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: limit-access
      hostPath:
        path: /Users/javedmulla/Downloads/k8s/practice/securityContext/3asg/Q3.txt
        type: FileOrCreate
status: {}
