apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: custom-cmd
  name: custom-cmd
spec:
  containers:
  - image: busybox
    name: custom-cmd
    command: ['top-analyzer','--all']
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
