apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: complex-pod
  name: complex-pod
spec:
  containers:
  - image: nginx
    name: app
    ports:
    - containerPort: 80
    resources: {}
  initContainers:
  - image:  busybox
    name: setup
    command: ['wget','-O-','google.com']
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
