apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: data-exchange
  name: data-exchange
spec:
  containers:
  - command:
    -  "/bin/sh"
    - "-c"
    - |
      counter=1; 
      while true; do
         echo "$counter" > /var/app/data/$((counter - 1))-data.txt;
         counter=$((counter+1));
         sleep 30;
      done
    image: nginx
    name: app
    resources: {}
    volumeMounts:
       - name: share
         mountPath: /var/app/data
  - image: busybox
    name: sidecar
    command:
    -  "/bin/sh"
    - "-c"
    - |
      while true; do
         echo "No of file produce: $(ls -l /var/app/data/ |wc -l)";
         sleep 60;
      done
    resources: {}
    volumeMounts:
       - name: share
         mountPath: /var/app/data
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: share
      emptyDir: {}
status: {}
