apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: app
  name: app
spec:
  containers:
  - image: busybox
    name: collector
    command: ["sh","-c","while true; do if [ \"$(cat /var/log/nginx/error.log \
              | grep 'error')\" != \"\" ]; then echo 'Error
discovered!'; fi; \
sleep 10; done"]
    volumeMounts:
      - name: sidecar
        mountPath: /var/log/nginx/
  - image: nginx
    name: app
    resources: {}
    volumeMounts:
      - name: sidecar
        mountPath: /var/log/nginx/
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes: 
    - name: sidecar
      emptyDir: {}
status: {}
