apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: main-app
  name: main-app
  namespace: monitoring
spec:
  containers:
  - image: httpd
    name: main-app
    resources: {}
    ports:
    - containerPort: 8080
  - image: prom/prometheus:latest
    name: monitoring
    resources: {}
    args: 
      - "--config.file=/etc/promethos/prometheus.yml"
    volumeMounts:
       - name: config
         mountPath: /etc/promethos/
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes: 
     - name: config
       configMap:
           name: prometheus-config
status: {}
