apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-1
    tier: frontend
    team: artemidis
  annotations:
    deployer: jm
  name: pod-1
spec:
  containers:
  - image: nginx
    name: pod-1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
