apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-2
    tier: backend
    team: artemidis
  name: pod-2
spec:
  containers:
  - image: nginx
    name: pod-2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
