apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-3
    tier: backend
    team: artemidis
  annotations:
    deployer: jm
  name: pod-3
spec:
  containers:
  - image: nginx
    name: pod-3
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
