apiVersion: v1
kind: Pod
metadata:
  name: scd
spec:
  containers:
  - image: alpine
    name: scd
    securityContext:
      capabilities:
        add: ["CAP_SYS_TIME"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
