apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: consumer
  name: consumer
spec:
  containers:
  - image: nginx
    name: consumer
    envFrom:
       - configMapRef:
            name: esc 
    volumeMounts:
       - name: test
         mountPath: /var/app
         readOnly: true
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name : test
      secret:
        secretName: ess 
status: {}
