apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: scd
  name: scd
spec:
  containers:
  - image: alpine
    name: scd
    resources: {}
    securityContext: 
       capabilities:
         add: ["CAP_SYS_TIME"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
