apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: 2q
  name: 2q
spec:
  containers:
  - image: mysql
    name: 2q
    resources: {}
    envFrom:
     -  secretRef:
         name: psw 
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
