apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: 3q
  name: 3q
spec:
  containers:
  - image: mysql
    name: 3q
    resources: {}
    volumeMounts:
       - name: map
         mountPath: /config
         readOnly: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
   - name: map
     secret:
       secretName:  psw
status: {}
