apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sqlapp
  name: sqlapp
spec:
  containers:
  - image: mysql
    name: sqlapp
    resources: {}
    env: 
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
             name: mysql
             key: password
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
